Create zh_CN translation
sk7725/BetaMindy pull request #158
Opened 2022-07-20 04:30 UTC by woodjecket

Create zh_CN translation.

2022-07-20 05:58 UTC, Weathercold requested changes

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +block.betamindy-present.description = A holly jolly block. Click to unwrap, you don't know what's inside!冬青枝装饰的好玩方块，点击以打开，你不会知道里面是什么的。
Remove English

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +block.betamindy-coin-source.description = Maintains the Anucoin balance, removing or creating endless Anucoins when connected to an Anubank. Sandbox only.\n[accent]Get Anucoins with a Trading Post an
Remove English

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +block.betamindy-cafe.name = 小餐馆
咖啡馆

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +item.betamindy-bittrium.description = 存在于 [#ef8aff]Portal Invasions[]。用作货币或在古代发明中使用。
Portal Invasions -> 传送门入侵

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +block.betamindy-repair-turret.name = 再生塔
修复塔？

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +ui.hardmode.intro = A [#ef8aff]Portal Invasion[] 开始了！
Portal Invasion -> 传送门入侵

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +ui.hardmode.demoend = Portal Invasion的演示版到此结束！更多内容尽请期待！
Portal Invasion -> 传送门入侵

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +ui.hardmode.title = Portal Invasion
传送门入侵

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +ui.trans.error = [scarlet]出现了一些错误。[] 请尝 [accent]刷新[]此页面。
`[scarlet]出现了一些错误。[]请尝式[accent]刷新[]此页面。`

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +purchase.invi-core.description =队伍所有核心无敌十秒钟\n\n然后治疗到满血
Add space after =

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +hint.breakCrystal = 引爆[accent]爆炸采掘器[] 以收获水晶，拆除得不到任何东西
Remove space

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +从更大的方块卸载流体和方块。\n[scarlet]已弃用，请用新版本代替[]
`block.betamindy-block-unpacker.description = `

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +block.betamindy-spinner-inert-infi.details =是无限惯性轴承，的确，我真不擅长起名。
Add space after =

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +block.betamindy-present.details = [scarlet]圣诞节[] [lime]快乐[] [scarlet]暨[] [lime]新[] [scarlet]年[] [lime]快乐[][scarlet]![]
Remove spaces

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +block.betamindy-payload-cannon.description =可以发射载荷。载荷的生命值越高，能够发射的距离越远，受到的伤害也越大，因此，造成的伤害也会越大。在[#98ffa9]inner range[]发射的载荷可以无伤害地发射。
inner range -> 安全范围内
Add space after =

2022-07-20 05:58 UTC, Weathercold commented on assets/bundles/bundle_zh_CN.properties
> +block.betamindy-ancient-store.description = 用猫猫币购买经典古老、再度流行的传说方块。商品每天更新！有些物品需要字节元素，与 [#ef8aff]Portal Invasion[]相关的物品在这里也可买到。
Portal Invasion -> 传送门入侵

2022-07-20 06:11 UTC, woodjecket commented on assets/bundles/bundle_zh_CN.properties
> +block.betamindy-repair-turret.name = 再生塔
看一下原文，这里得和原版修复塔区别开

2022-07-20 06:20 UTC, woodjecket commented
All above done

2022-07-20 15:20 UTC, Weathercold commented
还有一些错误没有修改
https://github.com/sk7725/BetaMindy/pull/158#discussion_r925200340, https://github.com/sk7725/BetaMindy/pull/158#discussion_r925197426, https://github.com/sk7725/BetaMindy/pull/158#discussion_r925197251, https://github.com/sk7725/BetaMindy/pull/158#discussion_r925196951
空格键都需要删掉，否则会在游戏内显示，例如`圣诞节 快乐 暨 新 年 快乐!`

2022-08-07 04:05 UTC, woodjecket commented
@sk7725 please merge

2022-09-26 04:47 UTC, merged